# Generated by Django 5.2.6 on 2025-09-21 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('grade_type', models.CharField(choices=[('worker', 'Worker'), ('staff', 'Staff')], help_text='Worker or Staff grade', max_length=20)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conveyance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mobile_bill', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salary Grade',
                'verbose_name_plural': 'Salary Grades',
                'db_table': 'employees_salary_grade',
                'ordering': ['grade_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft_skills', 'Soft Skills'), ('management', 'Management'), ('cognitive', 'Cognitive')], help_text='Skill category', max_length=20)),
                ('skills', models.JSONField(blank=True, default=list, help_text="Array of skills: ['skill1', 'skill2', ...]")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Metric',
                'verbose_name_plural': 'Skill Metrics',
                'db_table': 'employees_skill_metric',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='joining_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='children',
            field=models.JSONField(blank=True, default=list, help_text="Array of children information: [{'name': '', 'age': '', 'education': '', 'institute': ''}]"),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_issue',
            field=models.DateField(blank=True, help_text='Date of Issue', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, help_text='Date of Joining', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Alphabetic Knowledge', 'Alphabetic Knowledge'), ('JSC or Equivalent', 'JSC or Equivalent'), ('SSC or Equivalent', 'SSC or Equivalent'), ('HSC or Equivalent', 'HSC or Equivalent'), ("Hon's", "Hon's"), ("Master's", "Master's"), ('BSc', 'BSc'), ('MSc', 'MSc'), ('PhD', 'PhD')], help_text='Last Educational Status', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_address',
            field=models.EmailField(blank=True, help_text='Email address', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.JSONField(blank=True, default=dict, help_text="Emergency contact: {'name': '', 'mobile': '', 'relation': ''}"),
        ),
        migrations.AddField(
            model_name='employee',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='gross_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross Salary', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_work_experience',
            field=models.BooleanField(default=False, help_text='Do you have work experience?'),
        ),
        migrations.AddField(
            model_name='employee',
            name='height',
            field=models.CharField(blank=True, help_text='Height in cm', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='line',
            field=models.CharField(blank=True, help_text='Line 1, Line 2, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Mobile number with country code', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_bangla',
            field=models.CharField(blank=True, help_text='Name in Bangla', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_english',
            field=models.CharField(blank=True, help_text='Name in English', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(default='Bangladeshi', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='nid_number',
            field=models.CharField(blank=True, help_text='National ID Number', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='nominee',
            field=models.JSONField(blank=True, default=list, help_text="Array of nominees: [{'name': '', 'mobile': '', 'nidBirthCertificate': ''}]"),
        ),
        migrations.AddField(
            model_name='employee',
            name='off_day',
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address',
            field=models.JSONField(blank=True, default=dict, help_text="Permanent address: {'houseOwnerName': '', 'village': '', 'postOffice': '', 'upazilla': '', 'district': ''}"),
        ),
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, help_text='JPG, PNG or GIF up to 5MB', null=True, upload_to='employee_photos/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='present_address',
            field=models.JSONField(blank=True, default=dict, help_text="Present address: {'houseOwnerName': '', 'village': '', 'postOffice': '', 'upazilla': '', 'district': ''}"),
        ),
        migrations.AddField(
            model_name='employee',
            name='process_efficiency',
            field=models.JSONField(blank=True, default=list, help_text="Array of process efficiency: [{'itemDescription': '', 'processDeliveryPerHour': '', 'remarks': ''}]"),
        ),
        migrations.AddField(
            model_name='employee',
            name='process_expertise',
            field=models.JSONField(blank=True, default=list, help_text="Array of process expertise: [{'operation': '', 'machine': '', 'duration': ''}]"),
        ),
        migrations.AddField(
            model_name='employee',
            name='religion',
            field=models.CharField(default='Islam', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_components',
            field=models.JSONField(blank=True, default=dict, help_text="Salary components: {'basicSalary': {'enabled': true, 'amount': 0, 'custom': false}, 'houseRent': {...}, 'medicalAllowance': {...}, 'foodAllowance': {...}, 'conveyance': {...}, 'mobileBill': {...}}"),
        ),
        migrations.AddField(
            model_name='employee',
            name='spouse_name',
            field=models.CharField(blank=True, help_text="Husband/Wife's Name", max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject/Field of study', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor_name',
            field=models.CharField(blank=True, help_text="Supervisor's Name", max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit (free text field)', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='weight',
            field=models.CharField(blank=True, help_text='Weight in kg', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_experience',
            field=models.JSONField(blank=True, default=list, help_text="Array of work experience: [{'companyName': '', 'department': '', 'designation': '', 'salary': '', 'duration': ''}]"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level_of_work',
            field=models.CharField(choices=[('worker', 'Worker'), ('staff', 'Staff')], help_text='Worker or Staff', max_length=20),
        ),
        migrations.CreateModel(
            name='ProcessExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=200)),
                ('machine', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Process Expertise',
                'verbose_name_plural': 'Process Expertises',
                'db_table': 'employees_process_expertise',
                'ordering': ['operation', 'machine'],
                'unique_together': {('operation', 'machine')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_grade',
            field=models.ForeignKey(blank=True, help_text='Worker/Staff Salary Grade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.salarygrade'),
        ),
    ]
