# Generated by Django 5.2.6 on 2025-09-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_salarygrade_skillmetric_remove_employee_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processexpertise',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='processexpertise',
            name='machine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processexpertise',
            name='operation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
