# Generated by Django 5.2.6 on 2025-09-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20250922_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmetric',
            name='department',
            field=models.CharField(blank=True, help_text='Department for technical skills', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skillmetric',
            name='designation',
            field=models.CharField(blank=True, help_text='Designation for technical skills', max_length=200, null=True),
        ),
    ]
