# Generated by Django 5.2.6 on 2025-09-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_machine_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique employee identifier (e.g., EMP001) - auto-generated', max_length=20, unique=True),
        ),
    ]
