# Generated by Django 5.2.6 on 2025-09-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='generated_email',
            field=models.EmailField(blank=True, help_text='Generated email for login credentials', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='generated_password',
            field=models.CharField(blank=True, help_text='Generated password for login credentials', max_length=255, null=True),
        ),
    ]
