# Generated by Django 5.2.6 on 2025-09-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
