# Generated by Django 5.2.6 on 2025-09-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_managers_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='generated_password',
            field=models.CharField(blank=True, help_text='Generated password for HR users (stored in plain text for sharing)', max_length=128, null=True),
        ),
    ]
