# Generated by Django 5.2.6 on 2025-09-24 17:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0008_employee_generated_email_employee_generated_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_ratings', models.JSONField(blank=True, default=dict, help_text="Dictionary of skill ratings: {'skill_name': rating_value}")),
                ('overall_score', models.DecimalField(blank=True, decimal_places=1, help_text='Overall KPI score (0.0-5.0)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('assessment_year', models.PositiveIntegerField(help_text='Year of assessment')),
                ('assessment_month', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Month of assessment')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the assessment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, help_text='User who performed the assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_kpis', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Employee being rated', on_delete=django.db.models.deletion.CASCADE, related_name='kpi_ratings', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee KPI',
                'verbose_name_plural': 'Employee KPIs',
                'db_table': 'kpi_employee_kpi',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'assessment_year', 'assessment_month')},
            },
        ),
        migrations.CreateModel(
            name='KPIAssessmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action performed (created, updated, deleted, etc.)', max_length=50)),
                ('old_value', models.TextField(blank=True, help_text='Previous value')),
                ('new_value', models.TextField(blank=True, help_text='New value')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the change')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(help_text='Related KPI assessment', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='kpi.employeekpi')),
            ],
            options={
                'verbose_name': 'KPI Assessment History',
                'verbose_name_plural': 'KPI Assessment Histories',
                'db_table': 'kpi_assessment_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='KPITemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('designation', models.CharField(blank=True, help_text='Specific designation (null for all)', max_length=200, null=True)),
                ('department', models.CharField(blank=True, help_text='Specific department (null for all)', max_length=200, null=True)),
                ('soft_skills', models.JSONField(blank=True, default=list, help_text='List of soft skills for this template')),
                ('technical_skills', models.JSONField(blank=True, default=list, help_text='List of technical skills for this template')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpi_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI Template',
                'verbose_name_plural': 'KPI Templates',
                'db_table': 'kpi_template',
                'ordering': ['name'],
            },
        ),
    ]
