# Generated by Django 5.2.6 on 2025-09-24 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(help_text='Unique Asset ID', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Asset Name', max_length=200)),
                ('model', models.CharField(blank=True, help_text='Asset Model', max_length=100, null=True)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Office Equipment', 'Office Equipment'), ('Furniture', 'Furniture'), ('HVAC', 'HVAC'), ('Security', 'Security'), ('Machinery', 'Machinery'), ('Vehicles', 'Vehicles')], help_text='Asset Category', max_length=50)),
                ('department', models.CharField(help_text='Department', max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('Maintenance', 'Maintenance'), ('Damaged', 'Damaged'), ('Lost', 'Lost'), ('Retired', 'Retired')], default='Available', help_text='Current Status', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity')),
                ('value', models.DecimalField(decimal_places=2, help_text='Purchase Value', max_digits=12)),
                ('purchase_date', models.DateField(blank=True, help_text='Purchase Date', null=True)),
                ('depreciation_rate', models.PositiveIntegerField(default=20, help_text='Annual Depreciation Rate (%)')),
                ('vendor', models.CharField(blank=True, help_text='Vendor Name', max_length=200, null=True)),
                ('acc_voucher', models.CharField(blank=True, help_text='Accounting Voucher', max_length=100, null=True)),
                ('warranty_period', models.CharField(blank=True, help_text='Warranty Period', max_length=100, null=True)),
                ('assigned_to', models.CharField(default='Unassigned', help_text='Currently Assigned To', max_length=200)),
                ('assigned_to_id', models.CharField(blank=True, help_text='Assigned Employee ID', max_length=50, null=True)),
                ('assignment_date', models.DateField(blank=True, help_text='Assignment Date', null=True)),
                ('expected_return_date', models.DateField(blank=True, help_text='Expected Return Date', null=True)),
                ('assignment_reason', models.TextField(blank=True, help_text='Assignment Reason', null=True)),
                ('assigned_by', models.CharField(blank=True, help_text='Assigned By', max_length=200, null=True)),
                ('assignment_notes', models.TextField(blank=True, help_text='Assignment Notes', null=True)),
                ('assigned_condition', models.CharField(default='Good', help_text='Assigned Condition', max_length=50)),
                ('return_date', models.DateField(blank=True, help_text='Return Date', null=True)),
                ('return_condition', models.CharField(blank=True, help_text='Return Condition', max_length=50, null=True)),
                ('return_reason', models.TextField(blank=True, help_text='Return Reason', null=True)),
                ('returned_by', models.CharField(blank=True, help_text='Returned By', max_length=200, null=True)),
                ('return_notes', models.TextField(blank=True, help_text='Return Notes', null=True)),
                ('return_processed_date', models.DateField(blank=True, help_text='Return Processed Date', null=True)),
                ('disposal_date', models.DateField(blank=True, help_text='Disposal Date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Employee ID', max_length=50)),
                ('employee_name', models.CharField(help_text='Employee Name', max_length=200)),
                ('assignment_date', models.DateField(help_text='Assignment Date')),
                ('expected_return_date', models.DateField(blank=True, help_text='Expected Return Date', null=True)),
                ('assignment_reason', models.TextField(blank=True, help_text='Assignment Reason', null=True)),
                ('assigned_by', models.CharField(blank=True, help_text='Assigned By', max_length=200, null=True)),
                ('assigned_condition', models.CharField(choices=[('Good', 'Good'), ('Need Maintenance', 'Need Maintenance'), ('Lost', 'Lost')], default='Good', help_text='Assigned Condition', max_length=50)),
                ('assignment_notes', models.TextField(blank=True, help_text='Assignment Notes', null=True)),
                ('return_date', models.DateField(blank=True, help_text='Return Date', null=True)),
                ('return_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Need Maintenance', 'Need Maintenance'), ('Lost', 'Lost')], help_text='Return Condition', max_length=50, null=True)),
                ('return_reason', models.TextField(blank=True, help_text='Return Reason', null=True)),
                ('returned_by', models.CharField(blank=True, help_text='Returned By', max_length=200, null=True)),
                ('return_notes', models.TextField(blank=True, help_text='Return Notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Assignment',
                'verbose_name_plural': 'Asset Assignments',
                'ordering': ['-assignment_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='Scheduled Date')),
                ('completed_date', models.DateField(blank=True, help_text='Completed Date', null=True)),
                ('maintenance_provider', models.CharField(help_text='Maintenance Provider', max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Complete', 'Complete')], default='Pending', help_text='Status', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Maintenance Cost', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_history', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Maintenance',
                'verbose_name_plural': 'Asset Maintenance Records',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Employee ID', max_length=50)),
                ('employee_name', models.CharField(help_text='Employee Name', max_length=200)),
                ('assigned_date', models.DateField(help_text='Original Assignment Date')),
                ('return_date', models.DateField(help_text='Return Date')),
                ('return_condition', models.CharField(choices=[('Good', 'Good'), ('Need Maintenance', 'Need Maintenance'), ('Lost', 'Lost')], help_text='Return Condition', max_length=50)),
                ('return_reason', models.TextField(blank=True, help_text='Return Reason', null=True)),
                ('received_by', models.CharField(help_text='Received By', max_length=200)),
                ('return_notes', models.TextField(blank=True, help_text='Return Notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_history', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Return',
                'verbose_name_plural': 'Asset Returns',
                'ordering': ['-return_date'],
            },
        ),
    ]
