# Generated by Django 5.2.6 on 2025-09-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assigned_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Currently Assigned Quantity'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assigned_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity Assigned'),
        ),
    ]
