# Generated by Django 5.2.6 on 2025-09-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_assigned_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='assigned_quantity',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='assigned_quantity',
        ),
    ]
