# Generated by Django 5.2.6 on 2025-09-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_asset_assigned_quantity_remove_asset_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='need_maintenance',
            field=models.BooleanField(default=False, help_text='Asset needs maintenance'),
        ),
    ]
