# Generated by Django 5.2.6 on 2025-09-24 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0008_employee_generated_email_employee_generated_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_opening_id', models.CharField(help_text='Unique job opening identifier', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Job title', max_length=200)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full-time', max_length=20)),
                ('description', models.TextField(help_text='Detailed job description')),
                ('requirements', models.JSONField(default=list, help_text='List of job requirements')),
                ('experience_required', models.CharField(help_text='Required experience level', max_length=100)),
                ('salary_range', models.CharField(help_text='Salary range for the position', max_length=100)),
                ('manpower', models.PositiveIntegerField(default=1, help_text='Number of positions to fill')),
                ('posted_date', models.DateField(help_text='Date when job was posted')),
                ('deadline', models.DateField(help_text='Application deadline')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Closed', 'Closed')], default='Active', max_length=20)),
                ('applications_count', models.PositiveIntegerField(default=0, help_text='Number of applications received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_job_openings', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_openings', to='employees.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_openings', to='employees.designation')),
            ],
            options={
                'verbose_name': 'Job Opening',
                'verbose_name_plural': 'Job Openings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(help_text='Unique candidate identifier', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Full name of the candidate', max_length=200)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('location', models.CharField(help_text='Current location', max_length=200)),
                ('education', models.CharField(help_text='Educational background', max_length=200)),
                ('experience', models.CharField(help_text='Work experience', max_length=100)),
                ('skills', models.JSONField(default=list, help_text='List of candidate skills')),
                ('skill_ratings', models.JSONField(default=dict, help_text='Skill ratings (1-5 scale)')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Under Review', 'Under Review'), ('Available', 'Available'), ('Hired', 'Hired'), ('Did Not Qualify', 'Did Not Qualify'), ('Rejected', 'Rejected')], default='Applied', max_length=20)),
                ('applied_date', models.DateField(help_text='Date when candidate applied')),
                ('last_contact', models.DateField(help_text='Last contact date')),
                ('source', models.CharField(default='Manual Entry', help_text='How candidate found the job', max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Overall rating (0-5)', max_digits=3)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the candidate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_candidates', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='employees.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='employees.designation')),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment_module.jobopening')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interviewed', 'Interviewed'), ('Offered', 'Offered'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Application notes')),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment_module.candidate')),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment_module.jobopening')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-applied_date'],
                'unique_together': {('candidate', 'job_opening')},
            },
        ),
    ]
